#!/bin/bash

export PERL_MB_OPT="--install_base /opt/catalyst/perl5"
export PERL_MM_OPT="INSTALL_BASE=/opt/catalyst/perl5"
export PERL5LIB="/opt/catalyst/perl5/lib/perl5"

cd /opt/catalyst/app
cpanm --installdeps .
exec /opt/catalyst/app/script/greehost_spot_server.pl --restart --port 8080
